#spring.application.name=study-project

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bin_text
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 5MB

mybatis:
  type-aliases-package: com.neroll.pojo
  mapper-locations: classpath:com/neroll/mapper/*Mapper.xml

image-folder-absolute-path: D:/Work/IdeaProject/medical/src/main/resources/static/image/